WANDB:
  ENABLED: true
  DRYRUN: false
  PROJECT: dd3d
  GROUP: null
  TAGS: []
EVAL_ONLY: false
EVAL_ON_START: false
ONLY_REGISTER_DATASETS: false
OUTPUT_ROOT: ./outputs
SYNC_OUTPUT_DIR_S3:
  ENABLED: false
  ROOT_IN_S3: ???
  PERIOD: 1000
DATASET_ROOT: /scratch-second/egroenewald/synscapes
TMP_DIR: /scratch/egroenewald/tmp
DATASETS:
  TRAIN:
    NAME: synscapes_finetune_10_2
    CANONICAL_BOX3D_SIZES:
    - - 1.61876949
      - 3.89154523
      - 1.52969237
    - - 0.62806586
      - 0.82038497
      - 1.76784787
    - - 0.56898187
      - 1.77149234
      - 1.7237099
    - - 1.9134491
      - 5.15499603
      - 2.18998422
    - - 2.61168401
      - 9.22692319
      - 3.36492722
    - - 0.5390196
      - 1.08098042
      - 1.28392158
    - - 2.36044838
      - 15.56991038
      - 3.5289238
    - - 1.24489164
      - 2.51495357
      - 1.61402478
    DATASET_MAPPER: default
    NUM_CLASSES: 5
    MEAN_DEPTH_PER_LEVEL:
    - 32.594
    - 15.178
    - 8.424
    - 5.004
    - 4.662
    STD_DEPTH_PER_LEVEL:
    - 14.682
    - 7.139
    - 4.345
    - 2.399
    - 2.587
  TEST:
    NAME: synscapes_finetune_val
    NUSC_SAMPLE_AGGREGATE_IN_INFERENCE: false
    DATASET_MAPPER: default
FE:
  FPN:
    IN_FEATURES:
    - level3
    - level4
    - level5
    OUT_FEATURES: null
    OUT_CHANNELS: 256
    NORM: FrozenBN
    FUSE_TYPE: sum
  BUILDER: build_fcos_dla_fpn_backbone_p67
  BACKBONE:
    NAME: DLA-34
    OUT_FEATURES:
    - level3
    - level4
    - level5
    NORM: FrozenBN
  OUT_FEATURES: null
DD3D:
  IN_FEATURES: null
  NUM_CLASSES: 5
  FEATURE_LOCATIONS_OFFSET: none
  SIZES_OF_INTEREST:
  - 64
  - 128
  - 256
  - 512
  INFERENCE:
    DO_NMS: true
    DO_POSTPROCESS: true
    DO_BEV_NMS: false
    BEV_NMS_IOU_THRESH: 0.3
    NUSC_SAMPLE_AGGREGATE: false
  FCOS2D:
    _VERSION: v2
    NORM: BN
    NUM_CLS_CONVS: 4
    NUM_BOX_CONVS: 4
    USE_DEFORMABLE: false
    USE_SCALE: true
    BOX2D_SCALE_INIT_FACTOR: 1.0
    LOSS:
      ALPHA: 0.25
      GAMMA: 2.0
      LOC_LOSS_TYPE: giou
    INFERENCE:
      THRESH_WITH_CTR: true
      PRE_NMS_THRESH: 0.05
      PRE_NMS_TOPK: 1000
      POST_NMS_TOPK: 100
      NMS_THRESH: 0.5
  FCOS3D:
    NORM: FrozenBN
    NUM_CONVS: 4
    USE_DEFORMABLE: false
    USE_SCALE: true
    DEPTH_SCALE_INIT_FACTOR: 0.3
    PROJ_CTR_SCALE_INIT_FACTOR: 1.0
    PER_LEVEL_PREDICTORS: false
    SCALE_DEPTH_BY_FOCAL_LENGTHS: true
    SCALE_DEPTH_BY_FOCAL_LENGTHS_FACTOR: 500.0
    MEAN_DEPTH_PER_LEVEL:
    - 32.594
    - 15.178
    - 8.424
    - 5.004
    - 4.662
    STD_DEPTH_PER_LEVEL:
    - 14.682
    - 7.139
    - 4.345
    - 2.399
    - 2.587
    MIN_DEPTH: 0.1
    MAX_DEPTH: 80.0
    CANONICAL_BOX3D_SIZES:
    - - 1.61876949
      - 3.89154523
      - 1.52969237
    - - 0.62806586
      - 0.82038497
      - 1.76784787
    - - 0.56898187
      - 1.77149234
      - 1.7237099
    - - 1.9134491
      - 5.15499603
      - 2.18998422
    - - 2.61168401
      - 9.22692319
      - 3.36492722
    - - 0.5390196
      - 1.08098042
      - 1.28392158
    - - 2.36044838
      - 15.56991038
      - 3.5289238
    - - 1.24489164
      - 2.51495357
      - 1.61402478
    CLASS_AGNOSTIC_BOX3D: false
    PREDICT_ALLOCENTRIC_ROT: true
    PREDICT_DISTANCE: false
    LOSS:
      SMOOTH_L1_BETA: 0.05
      MAX_LOSS_PER_GROUP_DISENT: 20.0
      CONF_3D_TEMPERATURE: 1.0
      WEIGHT_BOX3D: 2.0
      WEIGHT_CONF3D: 1.0
    PREPARE_TARGET:
      CENTER_SAMPLE: true
      POS_RADIUS: 1.5
VIS:
  DATALOADER_ENABLED: false
  DATALOADER_PERIOD: 1000
  DATALOADER_MAX_NUM_SAMPLES: 10
  PREDICTIONS_ENABLED: false
  PREDICTIONS_MAX_NUM_SAMPLES: 20
  D2:
    DATALOADER:
      ENABLED: true
      SCALE: 1.0
      COLOR_MODE: image
    PREDICTIONS:
      ENABLED: true
      SCALE: 1.0
      COLOR_MODE: image
      THRESHOLD: 0.4
  BOX3D:
    DATALOADER:
      ENABLED: true
      SCALE: 1.0
      RENDER_LABELS: true
    PREDICTIONS:
      ENABLED: true
      SCALE: 1.0
      RENDER_LABELS: true
      THRESHOLD: 0.5
      MIN_DEPTH_CENTER: 0.0
INPUT:
  FORMAT: BGR
  AUG_ENABLED: true
  RESIZE:
    ENABLED: true
    MIN_SIZE_TRAIN:
    - 288
    - 304
    - 320
    - 336
    - 352
    - 368
    - 384
    - 400
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    MIN_SIZE_TRAIN_SAMPLING: choice
    MAX_SIZE_TRAIN: 10000
    MIN_SIZE_TEST: 384
    MAX_SIZE_TEST: 100000
  CROP:
    ENABLED: false
    TYPE: relative_range
    SIZE:
    - 0.9
    - 0.9
  RANDOM_FLIP:
    ENABLED: true
    HORIZONTAL: true
    VERTICAL: false
  COLOR_JITTER:
    ENABLED: true
    BRIGHTNESS:
    - 0.2
    - 0.2
    SATURATION:
    - 0.2
    - 0.2
    CONTRAST:
    - 0.2
    - 0.2
MODEL:
  DEVICE: cuda
  META_ARCHITECTURE: DD3D
  PIXEL_MEAN:
  - 103.53
  - 116.28
  - 123.675
  PIXEL_STD:
  - 57.375
  - 57.12
  - 58.395
  BOX2D_ON: true
  BOX3D_ON: true
  DEPTH_ON: false
DATALOADER:
  TRAIN:
    NUM_WORKERS: 0
    FILTER_EMPTY_ANNOTATIONS: true
    SAMPLER: RepeatFactorTrainingSampler
    REPEAT_THRESHOLD: 0.4
    ASPECT_RATIO_GROUPING: false
  TEST:
    NUM_WORKERS: 0
    SAMPLER: InferenceSampler
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 1.0e-05
  MOMENTUM: 0.9
  NESTEROV: false
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0001
  GAMMA: 0.1
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  STEPS:
  - 1200
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
  CLIP_GRADIENTS:
    ENABLED: false
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 100
  MIXED_PRECISION_ENABLED: true
  DDP_FIND_UNUSED_PARAMETERS: false
  ACCUMULATE_GRAD_BATCHES: 5
  SYNCBN_USE_LOCAL_WORKERS: false
  MAX_ITER: 1500
TEST:
  ENABLED: true
  EVAL_PERIOD: 100
  EVAL_ON_START: false
  ADDITIONAL_EVAL_STEPS: []
  IMS_PER_BATCH: 1
  AUG:
    ENABLED: true
    MIN_SIZES:
    - 320
    - 384
    - 448
    - 512
    - 576
    MAX_SIZE: 100000
    FLIP: true
EVALUATORS:
  KITTI3D:
    IOU_THRESHOLDS:
    - 0.5
    - 0.7
    ONLY_PREPARE_SUBMISSION: false

MODEL:
  CKPT: "local-data/models/dd3d.pth"
  WEIGHTS: "local-data/models/dd3d.pth"
